#!/bin/bash
##==============================================================================
##  Git Alias
##==============================================================================

shell="bash"
# Setting Alias for git, to manage dotfiles in $HOME with autocomplete
## git use __git_main for autocomplete git subcommands are _git_subcomand
alias gitdot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias gitdotsm='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME submodule'
alias gitdotsma='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME submodule add'
alias gitdotsmu='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME submodule update --remote --merge'

# shellcheck disable=SC2009
# shellcheck disable=SC2154
if [[ $(ps -p $$ | grep sh | awk '{print $(NF)}') = "$shell" ]]; then
    if [ -f "/usr/share/bash-completion/completions/git" ]; then
        # shellcheck disable=SC1091
        . /usr/share/bash-completion/completions/git
        __git_complete gitdot __git_main
        __git_complete gitdotsm _git_submodule
        __git_complete gitdotsma _git_submodule
        __git_complete gitdotsmu _git_submodule
        __git_complete gitrdot __git_main
        __git_complete gitrdotsm _git_submodule
        __git_complete gitrdotsma _git_submodule
        __git_complete gitrdotsmu _git_submodule
   fi
fi
