#!/bin/bash
##  +-----------------------------------+-----------------------------------+
##  |                                                                       |
##  | Copyright (c) 2018-2020, Andres Gongora <mail@andresgongora.com>.     |
##  |                                                                       |
##  | This program is free software: you can redistribute it and/or modify  |
##  | it under the terms of the GNU General Public License as published by  |
##  | the Free Software Foundation, either version 3 of the License, or     |
##  | (at your option) any later version.                                   |
##  |                                                                       |
##  | This program is distributed in the hope that it will be useful,       |
##  | but WITHOUT ANY WARRANTY; without even the implied warranty of        |
##  | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         |
##  | GNU General Public License for more details.                          |
##  |                                                                       |
##  | You should have received a copy of the GNU General Public License     |
##  | along with this program. If not, see <http://www.gnu.org/licenses/>.  |
##  |                                                                       |
##  +-----------------------------------------------------------------------+
##  DESCRIPTION:
##  Overrides 'ls' command to be more useful/easier to read. The following
##  main modifications are applied:
##  - Colorized
##  - Human readable output
##  - Long timestamp
##
##  HOW IF WORKS:
##  - If no arguments passed
##      Show . and ..
##      Shows directories
##      Shows visible files
##      Shows hidden directories
##      Shows hidden files
##  - else
##      Runs with argument, but sorts directories first and prints color
##
##  DEV NOTES:
##
##  shopt -s extglob
##      This must be enabled for extglob wildcards to work (eg !). for bash
##      https://www.zsh.org/mla/users/2006/msg00728.html for zsh
##
##  files=$(/usr/bin/ls -U * 2> /dev/null | wc -l)
##      Create a list of all files in '*' and count it with wc -l
##      If zero there is no file. -U disables sorting for
##      shorter response times.
##
##  hidden_files=$(/usr/bin/ls -U -d .[^.]* 2> /dev/null | wc -l)
##      Same as above, but for '.[^.]*', which includes all
##      hidden files but ommits '.' and '..' .
##
##  .[^.]*
##      Anything starting with '.', followed by one char that can not be
##      '.', and then as many (or any) characters as wanted.
## LS parameters:
## -U do not sort
## -a show hidden files and folders
## -l long list format
## -A list all except . and ..
## --color-auto show colors on output
## --human-readable print size in k,m,g
## --time-style date/time format used full-iso, long-iso, iso, locale, or +FORMAT.FORMAT is interpreted like in date(1)
## --group-directories-first put folders then files
## To modify the time styel use the TS variable
## Current date format day of the month-month-year %t (tab) time(24hs format)
##==============================================================================
##  BETTER LS
##==============================================================================

function better_ls()
{
    # shopt -s extglob
    local LS=$(command -v ls)
    local TS="+%d-%m-%Y%t%R"

    ## IF NO ARGUMENTS PASSED -> run better ls version on current folder
    ## OR IF ARGUMENT IS A PATH -> run better ls version on specified folder
    if [ $# -eq 0 ]; then

        ## IF THE CURRENT FOLDER IS NOT EMPTY -> Display all
        files=$($LS -Ua 2> /dev/null | wc -l)
        if [ "$files" != "0" ]
        then
            ## LIST DIR AND PARENT
            ## - Convert dir name
            ## - Check that not at /, because there is no parent
            $LS -d {.,..,*} -lA --color=auto --human-readable \
                --time-style=$TS --group-directories-first 2>/dev/null;

            ## List hidden folders and files (only if they exist)
            hidden_files=$($LS -U -d .[^.]* 2> /dev/null | wc -l)
            if [ "$hidden_files" != "0" ]
            then
                echo ""
                $LS -d .[^.]* -l --color=auto --hide='..' \
                    --human-readable --time-style=$TS \
                    --group-directories-first;
            fi

        ## IF THE TARGET DIR IS EMPTY -> List . and ..
        else
            $LS -d {.,..} -lA --color=auto --human-readable \
                --time-style=$TS --group-directories-first;
        fi

    ## IF ARGUMENT IS A SINGLE PATH
    ## Move to target dir
    ## Call recursively with no arguments
    ## Restore dir
    elif [ $# -eq 1 ] && [ -d "$1" ]; then
        local current_pwd="$PWD"
        'cd' "$1/" || exit
        better_ls
        'cd' "$current_pwd" || exit

    ## IF ARGUMENT IS A SINGLE FILE
    elif [ $# -eq 1 ] && [ -f "$1" ]; then
        $LS -l --color=auto --human-readable --time-style=$TS "$1"

    ## IF ARGUMENTS PASSED -> run standard ls but with some tweaks (eg: colors)
    else
        $LS --color=auto --human-readable --time-style=$TS \
            --group-directories-first "$@";
    fi
}

# Call main function
better_ls "$@"
