#!/bin/bash

### ARCHIVE EXTRACTION saw it in distro tube youtube channel.
# usage: ex <file>
show_help() {
 cat << EOF
 Usage: ex <file>
 Generically extract content of compressed and packaged files.

EOF
}

function ex () {
if [[ "$#" -eq 0 || -n "$1" || -z "$1" ]]
then
    show_help
else
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1   ;;
            *.tar.gz)    tar xzf $1   ;;
            *.bz2)       bunzip2 $1   ;;
            *.rar)       unrar x $1   ;;
            *.gz)        gunzip $1    ;;
            *.tar)       tar xf $1    ;;
            *.tbz2)      tar xjf $1   ;;
            *.tgz)       tar xzf $1   ;;
            *.zip)       unzip $1     ;;
            *.Z)         uncompress $1;;
            *.7z)        7z x $1      ;;
            *.deb)       ar x $1      ;;
            *.tar.xz)    tar xf $1    ;;
            *.tar.zst)   unzstd $1    ;;
            *)           echo "'$1' cannot be extracted via ex()" ;;
        esac
    else
        echo "'$1' is not a valid file"
        exit 1
    fi
fi
exit 0
}

# Call main function
ex "$1"
