#!/bin/bash

show_help() {
 cat << EOF
 Usage: memo [PARAMETER]
 Show in fzf for easier view the info on the defined alias or custom commands

EOF
}

function memo()
{
if [ "$#" -eq 0 ]
then
    show_help
else
    # Telling closing condition
    printf "Presione ESC para finalizar\n"
    # Check that there is only one parameter
    if [ $# -eq 1 ]
    then
        case $1 in
           # Compara el valor y asigna el comando a mostrar para el help, agregar un case a futuro
           "alias") grep -R "alias " "$HOME"/.shell_config/myalias/ | awk -F":" '{print $2}' | fzf;;
           "commands") < "$HOME"/.shell_config/commands/resumen fzf ;;
           *) printf "Las opciones disponibles actualmente son \nalias\ncommands\n" ;;
        esac
    else
       printf "El comando solo acepta un parámetro\nLas opciones disponibles actualmente son:\nalias\ncommands\n"
    fi
    return 0
fi
}

# Call main function
memo "$@"
